import './globals.css'
import Providers from './Providers'
import type { Metadata } from 'next'
import { Roboto_Flex } from 'next/font/google'

const font = Roboto_Flex({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Barangay Management System',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: React.ReactNode
}

function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout